CLASS LHC_ZZSTR_STUD_ADM_TAB_03003 DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
        IMPORTING
           REQUEST requested_authorizations FOR ZzstrStudAdmTab03003
        RESULT result.
ENDCLASS.

CLASS LHC_ZZSTR_STUD_ADM_TAB_03003 IMPLEMENTATION.
  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.
ENDCLASS.
